### ISSUE TITLE
Sprockets fails when the css_dir and the js_dir are overwritten

### ISSUE THREAD

**Issue by andreamoro** [middleman/middleman-sprockets#128] opened 2017-04-28 22:31 UTC
## Expected behavior and actual behavior
I would like to change the path of my js_dir folder, and in fact I did it in the config.rb file. However, by doing so sprockets fails to interpret and compile file that includes the require instructions.
Not only that. By hitting an existing file in the address bar, sprockets raise the following exception 

`throw Error("Sprockets::FileNotFound: couldn't find file '.....`

## Steps to reproduce the problem (from a clean middleman installation) or example repo
I updated a demo site below to demonstrate the problem.
https://github.com/andreamoro/middleman-sprockets-test

## Additional information

- Ruby version: 2.4.1, 2.3.1
- Middleman version: 4
- Middleman Sprockets version: 4.1.0, 4.0.0
- OS version: Sierra

**Comment by andreamoro** [comment] 2017-04-29 08:30
Just in case, created a testing git 
https://github.com/andreamoro/middleman-sprockets-test

Was too tired yesterday night.

**Comment by andreamoro** [comment] 2017-04-29 08:37
I've tried also to update to sprocket 4.0.0.beta4, just to test whether the issue was due to a dependency, but this does not seem to be the case.

**Comment by stevenosloan** [comment] 2017-05-01 04:01
I may be missing something, but I think your problem lies in your config.

```ruby
  set :dir, '/' + I18n.locale.to_s + '/'
  set :css_dir, config[:dir] + 'javascripts'
```
Since I18n is defaulting to "en", the css_dir ends up getting set to `/en/javascripts` -- that'll be an issue for two reasons:
1. css probably isn't in the javascripts directory ;)
2. your css isn't in `/en/**`, you'd want to set the css_dir to `content/stylesheets` to match where they actually are

I'm not really that familiar with I18n, but I imagine you'd want to leave your css/js at `source/javascripts`, `source/stylesheets` and not nest them in the I18n templates directory. At any rate, your css_dir & js_dir need to be set to the actual location on disk relative to the source directory, not the output directory.

**Comment by andreamoro** [comment] 2017-05-02 11:28
Hi @stevenosloan 

Thanks for returning to me. 

Conversely to your expectations, my javascript folder is hosted in the /en and /it subfolder once built. This is because I need both versions of the site to be hosted independently.
The same is happening for the css folder.

The css_dir & js_dir remapping above are meant to set the actual location on disk relative to the source directory, which is source/content/javascript and source/content/stylesheets.

I've created a gist here https://github.com/andreamoro/middleman-sprockets-test for you to have a look if you have some time.

**Comment by stevenosloan** [comment] 2017-05-02 16:49
You should set it to `content/javascripts` or `content/stylesheets` then -- with `config[:dir] + XX` it gets set to `/en/XX` or `/it/XX` which is not where the **source** files are on disk.

**Comment by andreamoro** [comment] 2017-05-02 17:30
No worries for the close / reopen. It happens, though I can't see your answer here. Thankfully I have in the inbox.

By the time I answered above and in the light of your previous message, I did some experiments to understand better how that path stuff works, and I arrived to the conclusion that both css_dir and js_dir required ```'./content/stylesheets'```.

However, by doing so the site seems to respond just in part to what the expectations and the logic would suggest. 

The site.js in source/javascripts is able to include content in source/contente/javascripts (and that's fine). However that file is outside what it will be my destination built directory.
The same site.js file hosted in source/content/javascripts throw the following error ```Sprockets::FileNotFound: en/stylesheets/site.css```.

It seems like the reported path is relative to the built directory rather than the source. I'm not sure what I am missing, but I have updated the gist so to make sure you can check my progress and help me understanding where I am failing?

**Comment by stevenosloan** [comment] 2017-05-02 17:47
heh, yeah I had typed that up and was doing some digging to figure out it wasn't really correct. 

There's some interaction between the ordering of how `I18n` reproduces assets and how middleman-sprockets processes them that are pretty edge casy. (if you activate sprockets after i18n things get even more interesting) There's a baseline assumption that sprockets processed assets aren't going to be moved that I got wrong -- so looking into some workarounds for that.

**Comment by andreamoro** [comment] 2017-05-02 17:50
Good to know that it's not me getting this completely wrong. Also because on the CSS side, I always though I was using sprockets by simply having .scss files and @import instructions. 
That's not the case, because it seems sprockets inclusions on a css file requires a ```*=```. 
Can you confirm this is the case?

**Comment by andreamoro** [comment] 2017-05-02 18:40
Was able to reproduce the above ```I18n``` behaviour (I think) and I have updated my gist to document the experiments I've done. 

Weird results indeed.

**Comment by stevenosloan** [comment] 2017-05-02 18:48
Gotta move to some other things before cleaning this up -- but I think I've got a fix up on

IIRC you can use that from your gemfile like:
```
gem "middleman-sprockets", github: "middleman/middleman-sprockets",
                           branch: "I128-respect_proxied_assets"
```

Then
- move sprockets activation *after* I18n
- use `content/javascripts` for js_dir & `content/stylesheets` for css_dir.

**Comment by andreamoro** [comment] 2017-05-02 18:56
It seems working as expected this, both the css and js in the content folder as well as in the rendered locale folder are now rendering correctly.

Still unsure whether the ```//= require _test ``` or ```@import _test``` is the right syntax for the CSS, as both seems working fine now.

Would you expect major changes to the final commit, or can I start integrating into my master project?

**Comment by vvasabi** [comment] 2017-05-02 19:31
`//= require _test` is done through Sprockets but won’t give the parent file access to all the variables, mixins, _etc._, within `_test.scss`. `@import "test"` is done through Sass and will give the parent file access to all the things declared within the `@import`ed file. Either way works, but you may choose one over another due to this subtle difference.

**Comment by andreamoro** [comment] 2017-05-02 19:36
Thanks for clarifying the difference. That explains why I never experienced problems whilst concatenating the resources before. I was using Sass and not Sprocket as I was thinking. 

Need to get re-aligned with all these new web dev things. Lots have happened in the past 10 years.

**Comment by stevenosloan** [comment] 2017-05-04 15:11
@andreamoro I'm not expecting much to change, especially from a end-user standpoint. Just need some time to get some test cases in and investigate why some of the tests in CI failed.

And thanks @vvasabi, that's much better than I would have explained it :)

**Comment by stevenosloan** [comment] 2017-06-28 04:28
Apologies for taking so long finishing this up, every time I've come back I've lost context and can't seem to get specs written that will fail for the reasons outlined here & fixed in the `I128-respect_proxied_assets` branch. If anyone has some time to dig into that it'd be 💯

**Closed** 2017-08-28 17:14 UTC
